In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**DATA PREPARATION**

In [ ]:
df = pd.read_csv(r"C:\Users\USER\Desktop\python projects\food_reviews (1).csv")
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [ ]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [ ]:
df.columns.str.strip().str.lower().str.replace(" ","_")

Index(['id', 'productid', 'userid', 'profilename', 'helpfulnessnumerator',
       'helpfulnessdenominator', 'score', 'time', 'summary', 'text'],
      dtype='object')

In [ ]:
df.shape

(568454, 10)

In [ ]:
df.dtypes

Id                         int64
ProductId                 object
UserId                    object
ProfileName               object
HelpfulnessNumerator       int64
HelpfulnessDenominator     int64
Score                      int64
Time                       int64
Summary                   object
Text                      object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [ ]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [ ]:
df.head(2)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...

In [ ]:
df["ProfileName"].fillna("NAN", inplace = True)

C:\Users\USER\AppData\Local\Temp\ipykernel_9676\1507727421.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["ProfileName"].fillna("NAN", inplace = True)

In [ ]:
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName                0
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [ ]:
df["Summary"].fillna("unkown", inplace = True)

C:\Users\USER\AppData\Local\Temp\ipykernel_9676\552425762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Summary"].fillna("unkown", inplace = True)

In [ ]:
df.isnull().mean()*100

Id                        0.0
ProductId                 0.0
UserId                    0.0
ProfileName               0.0
HelpfulnessNumerator      0.0
HelpfulnessDenominator    0.0
Score                     0.0
Time                      0.0
Summary                   0.0
Text                      0.0
dtype: float64

In [ ]:
df.value_counts()

Id      ProductId   UserId          ProfileName                HelpfulnessNumerator  HelpfulnessDenominator  Score  Time        Summary                                 Text
1       B001E4KFG0  A3SGXH7AUHU8GW  delmartian                 1                     1                       5      1303862400  Good Quality Dog Food                   I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
378972  B005ZBZLPI  A3J49NRVZDJ6ZY  BenW                       1                     1                       4      1323129600  Nice Flavor, Dark But Not Overwhelming  Pleasantly surprised by the taste...very dark (reminds me of Green Mountain's Dark Magic), but not quite so overwhelming and has a very subtle aftertaste.  Packaging (most of the "cup" is a filter mesh) is great...other companies should follow suit.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
378966  B005ZBZLPI  A2QCBNA4IC2AIA  S. C. Gawers               1                     1                       5      1330905600  GREAT TASTE!!!                          The first thing I would like to say is that the bottom of the k cup is a mesh not plastic but it still goes in my keurig machine just like a regular plastic bottom k cup. I don't understand what the fuss is all about.  It does look a little different from what you may be used to seeing, but works just the same. Now as to the taste of the coffee, I think that it is a full body flavor. If I want a strong taste I brew regular size amd if I wish to have a milder flavor I will brew the largest cup size, I have the best of both worlds. I immediately went on subscribe and save.  I order 5 boxes at a time.  Love the flavor of this coffee.  Now to my complaint. I notice today that the price of each box has increased approximately $2.54 a box and that is within about three weeks time. Now I really love the convenience of my Keurig, however eventually the price of the k cups will reach a price that will cause me to say NO MORE. That time is approaching quickly. This brand started out to be more reasonable than most, but with this price jump in the last three weeks I am afraid they (the company) will soon be way overpriced as are the other brands.  Again I will say I do love the flavor of this coffee. Did I mention my husband likes it as well and he normally does not like decaf coffee.    1
378967  B005ZBZLPI  A24QCBPKNN68S6  MikeG                      1                     1                       5      1330128000  Great Coffee                            I read the reviews and got nervous at first.<br />I'm happy I tried it and now I have a monthly subscription, loving the coffee.<br />This is one of the best decafs I've had to date.<br />The lack of plastic is good too, as it seems such a waste.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
378968  B005ZBZLPI  A3IPWXEY66PIE7  Linda Bille "Coffee Girl"  1                     1                       4      1330041600  They work in Keurig machines...         I freaked out when I saw the strange design of this coffee pod - definitely not your wasteful, landfill-clogging- feeling- guilty- about-  drinking- it K-cup.  However it works just fine in the Keurig machine and produces a rather nice, bold, cup of decaf.  I would rate it beneath the Tully's French Roast and above any other decaf I have had.  I would recommend it and would like to try the regular blends.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
189480  B001EO5Q64  A2KGE7SH7QKEQ7  Debit Card "Brenda"        1                     1                       5      1313884800  Coconut oil                             I love this stuff. The taste is awesome and its very healthy for you. I will be ordering it again.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
189479  B001EO5Q64  A28KGML0DW9DL3  N. Mokhariwale             1                     1                       5      1314489600  Heavenly taste!                         I always had the impression that coconut oil is pungent with a strong taste. Probably I had only tried refined coconut oil.<br /><br />On the contrary Nutiva is heavenly - untouched, unbromated, just out of the coconut taste!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
189478  B001EO5Q64  A1EMI6JHRFND65  Sublime                    1                     1                       5      1316736000  Multi-Use!                              Coconut oil is not widely known for its health benefits (at least in the US) so I am trying to spread the word.  It is great for cooking as a vegetable oil substitute and butter substitute in many recipes.  Of course it contains no salt, so if a recipe is counting on the salt from butter as flavor (easy example is toast), then you may want to add some salt separately.  But of course, most of us can use less salt in our diet.<br /><br />Also, this is great for dry skin.  It might take a few (5-10) minutes to absorb completely, but it works wonders.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
189477  B001EO5Q64  AQGV8L76V1BME   J. Forte "Speaker40"       1                     1                       5      1317686400  Great product                           Outstanding product in quality and packaging. We have replaced our standard corn or vegetable oil with the coconut oil. Healthier and tastes better.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
568454  B001LR2CU2  A3LGQPJCZVL9UC  srfell17                   0                     0                       5      1338422400  Great Honey                             I am very satisfied ,product is as advertised, I use it on cereal, with raw vinegar, and as a general sweetner.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Name: count, Length: 568454, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Text"].str.len().describe()

count    568454.000000
mean        436.222083
std         445.339741
min          12.000000
25%         179.000000
50%         302.000000
75%         527.000000
max       21409.000000
Name: Text, dtype: float64

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.head(2)

,id,productid,userid,profilename,helpfulnessnumerator,helpfulnessdenominator,score,time,summary,text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...

In [ ]:
df["text"] = df["text"].str.lower()

In [ ]:
df["text"].head(3)

0    i have bought several of the vitality canned d...
1    product arrived labeled as jumbo salted peanut...
2    this is a confection that has been around a fe...
Name: text, dtype: object

In [ ]:
import re
all_punct = df["text"].apply(lambda t: re.findall(r"[^\w\s]", t))
unique_chars = set(char for row in all_punct for char in row)
print(unique_chars)

{'-', '×', '£', ';', '\x13', '\xad', '>', '¦', '°', '(', '\x07', ',', '»', '[', '?', '}', '\x99', ']', '¬', '=', '·', '.', '\x0f', '$', '^', '~', '{', '¨', '@', '<', '`', '/', "'", '\x06', '*', '#', '%', '©', '«', '±', '®', '!', ':', '\x8c', '&', '"', '+', '¢', '\x10', '|', '\\', ')', '§'}

In [ ]:
count_punct = df["text"].apply(lambda t: len(re.findall (r"[^\w\s]", t)))
count_punct

0          3
1          7
2         18
3          5
4          5
          ..
568449     8
568450     9
568451    11
568452     3
568453     5
Name: text, Length: 568454, dtype: int64

In [ ]:
df["clean_text"] = df["text"].str.replace(r"[^\w\s!?]", " ", regex = True)

In [ ]:
df["clean_text"] = df["clean_text"].str.replace(r"http\S+|www\S+", "", regex=True)
df["clean_text"] = df["clean_text"].str.replace(r"<.*?>", "", regex=True)
df["clean_text"] = df["clean_text"].str.replace(r"@\w+", "", regex=True)
df["clean_text"] = df["clean_text"].str.replace(r"#", "", regex=True)
df["clean_text"] = df["clean_text"].str.replace(r"\S+@\S+", "", regex=True)

In [ ]:
import re
import contractions
import emoji

def clean_text(text):
    text = text.lower()
    text = contractions.fix(text)                       
    text = emoji.demojize(text, delimiters=(" ", " "))  
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = re.sub(r"#", "", text)
    text = re.sub(r"\S+@\S+", " ", text)
    text = re.sub(r"(.)\1{2,}", r"\1\1", text)            # soooo -> soo
    text = re.sub(r"[^\w\s!?]", " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_text"] = df["text"].apply(clean_text)

In [ ]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")   
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [ ]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
df["tokens"] = df["clean_text"].apply(word_tokenize)

In [ ]:
df["tokens"].head(2)

0    [i, have, bought, several, of, the, vitality, ...
1    [product, arrived, labeled, as, jumbo, salted,...
Name: tokens, dtype: object

In [ ]:
stop_words = set(stopwords.words("english"))
negation_words = {"not", "no", "never", "nor"}
stop_words = stop_words - negation_words

In [ ]:
df["tokens_clean"] = df["tokens"].apply(lambda x: [w for w in x if w not in stop_words])
df["tokens_clean"].head(2)

0    [bought, several, vitality, canned, dog, food,...
1    [product, arrived, labeled, jumbo, salted, pea...
Name: tokens_clean, dtype: object